version: "3.11"
services:
  app :
    build: ./
    ports:
      - '8000:8000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=coffe_shop
    ports:
      - '5432:5432'